config/routes.rb
Rails.application.routes.draw do
  resources :musics
  resources :songs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/music.rb
class Music < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  before_action :set_music, only: [:show, :edit, :update, :destroy]

  # GET /musics
  # GET /musics.json
  def index
    @musics = Music.all
  end

  # GET /musics/1
  # GET /musics/1.json
  def show
  end

  # GET /musics/new
  def new
    @music = Music.new
  end

  # GET /musics/1/edit
  def edit
  end

  # POST /musics
  # POST /musics.json
  def create
    @music = Music.new(music_params)

    respond_to do |format|
      if @music.save
        format.html { redirect_to @music, notice: 'Music was successfully created.' }
        format.json { render :show, status: :created, location: @music }
      else
        format.html { render :new }
        format.json { render json: @music.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /musics/1
  # PATCH/PUT /musics/1.json
  def update
    respond_to do |format|
      if @music.update(music_params)
        format.html { redirect_to @music, notice: 'Music was successfully updated.' }
        format.json { render :show, status: :ok, location: @music }
      else
        format.html { render :edit }
        format.json { render json: @music.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /musics/1
  # DELETE /musics/1.json
  def destroy
    @music.destroy
    respond_to do |format|
      format.html { redirect_to musics_url, notice: 'Music was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_music
      @music = Music.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def music_params
      params.require(:music).permit(:name, :artist, :video_link, :bpm, :bg_link, :notes_link, :img_link , :created_by, :tone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Worship</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/musics/_form.html.erb
<%= form_with(model: music, local: true) do |form| %>
  <% if music.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(music.errors.count, "error") %> prohibited this music from being saved:</h2>

      <ul>
      <% music.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :music_name %>
  </div>

  <div class="field">
    <%= form.label :artist %>
    <%= form.text_field :artist, id: :music_artist %>
  </div>

  <div class="field">
    <%= form.label :video_link %>
    <%= form.text_field :video_link, id: :music_video_link %>
  </div>

  <div class="field">
    <%= form.label :bpm %>
    <%= form.number_field :bpm, id: :music_bpm %>
  </div>

  <div class="field">
    <%= form.label :bg_link %>
    <%= form.text_field :bg_link, id: :music_bg_link %>
  </div>

  <div class="field">
    <%= form.label :notes_link %>
    <%= form.text_field :notes_link, id: :music_notes_link %>
  </div>

  <div class="field">
    <%= form.label :img_link %>
    <%= form.text_field :img_link, id: :music_img_link %>
  </div>
  <div class="field">
    <%= form.label :tone %>
    <%= form.text_field :tone, id: :music_tone %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/musics/edit.html.erb
<h1>Editing Music</h1>

<%= render 'form', music: @music %>

<%= link_to 'Show', @music %> |
<%= link_to 'Back', musics_path %>

app/views/musics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Musics</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Artist</th>
      <th>Video link</th>
      <th>Bpm</th>
      <th>Bg link</th>
      <th>Notes link</th>
      <th>Created by</th>
      <th>Tone</th>
      <th>Imglink</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @musics.each do |music| %>
      <tr>
        <td><%= music.name %></td>
        <td><%= music.artist %></td>
        <td><%= music.video_link %></td>
        <td><%= music.bpm %></td>
        <td><%= music.bg_link %></td>
        <td><%= music.notes_link %></td>
        <td><%= music.created_by %></td>
        <td><%= music.tone %></td>
        <td><%= music.img_link %></td>
        <td><%= link_to 'Shofw', music %></td>
        <td><%= link_to 'Edit', edit_music_path(music) %></td>
        <td><%= link_to 'Destroy', music, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Music', new_music_path %>

app/views/musics/new.html.erb
<h1>New Music</h1>

<%= render 'form', music: @music %>

<%= link_to 'Back', musics_path %>

app/views/musics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @music.name %>
</p>

<p>
  <strong>Artist:</strong>
  <%= @music.artist %>
</p>

<p>
  <strong>Videolink:</strong>
  <%= @music.video_link %>
</p>

<p>
  <strong>Bpm:</strong>
  <%= @music.bpm %>
</p>

<p>
  <strong>Bglink:</strong>
  <%= @music.bg_link %>
</p>

<p>
  <strong>Noteslink:</strong>
  <%= @music.notes_link %>
</p>

<p>
  <strong>Tone:</strong>
  <%= @music.tone %>
</p>
<p>
  <strong>Imglink:</strong>
  <%= @music.img_link %>
</p>

<p>
  <strong>Created By:</strong>
  <%= @music.created_by %>
</p>


<%= link_to 'Edit', edit_music_path(@music) %> |
<%= link_to 'Back', musics_path %>